dependencies:
- name: activiti-cloud-acceptance-tests
  repository: https://almerico.github.io/helmrepo
  version: 7.0.19
- name: activiti-cloud-full-example
  repository: https://almerico.github.io/helmrepo
  version: 0.0.60
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
